#!/usr/bin/env bash
set -euo pipefail
WS="/tmp/kavia/workspace/code-generation/voice-assistant-documentation-236916-236917/Documentation"
mkdir -p "$WS/source" "$WS/build" "$WS/.logs" && cd "$WS"
# conf.py only if missing
if [ ! -f "$WS/source/conf.py" ]; then
  cat > "$WS/source/conf.py" <<'PY'
# -*- coding: utf-8 -*-
project = 'Voice Assistant Docs'
author = 'AutoGenerated'
release = '0.1.0'
master_doc = 'index'
extensions = []
templates_path = ['_templates']
html_static_path = ['_static']
html_theme = 'alabaster'
PY
fi
# index and usage only if missing
if [ ! -f "$WS/source/index.rst" ]; then
  cat > "$WS/source/index.rst" <<'RST'
Welcome
=======

.. toctree::
   :maxdepth: 2

   usage

RST
fi
if [ ! -f "$WS/source/usage.rst" ]; then
  cat > "$WS/source/usage.rst" <<'RST'
Usage
=====

Sample usage documentation.
RST
fi
# Makefile delegates to build.sh
if [ ! -f "$WS/Makefile" ]; then
  cat > "$WS/Makefile" <<'MK'
.PHONY: html
html:
	@./build.sh
MK
fi
# build.sh computes WS at runtime (idempotent)
if [ ! -f "$WS/build.sh" ]; then
  cat > "$WS/build.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
WS="$(pwd)"
mkdir -p "$WS/build"
# use python3 -m sphinx to avoid relying on a specific sphinx binary location
python3 -m sphinx -b html "$WS/source" "$WS/build"
BASH
  chmod +x "$WS/build.sh"
fi
# preview.sh: safe start/stop, writes pid, appends logs
if [ ! -f "$WS/preview.sh" ]; then
  cat > "$WS/preview.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
WS="$(pwd)"
LOG_DIR="$WS/.logs"
mkdir -p "$LOG_DIR" "$WS/build"
PID_FILE="$WS/preview.pid"
LOG_FILE="$LOG_DIR/preview.log"
PORT=${PORT:-8000}
HOST=${HOST:-127.0.0.1}
# If pid exists and process alive, echo pid and exit 0
if [ -f "$PID_FILE" ]; then
  pid=$(cat "$PID_FILE" 2>/dev/null || true)
  if [ -n "$pid" ] && ps -p "$pid" >/dev/null 2>&1; then
    echo "$pid"
    exit 0
  else
    rm -f "$PID_FILE"
  fi
fi
# Start server bound to localhost; append logs
cd "$WS/build"
# Start in background, redirect stdout/stderr to log file and capture pid
( python3 -u -m http.server "$PORT" --bind "$HOST" >> "$LOG_FILE" 2>&1 ) &
pid=$!
# Save pid atomically
printf "%s" "$pid" > "$PID_FILE" || { echo "failed to write pid" >&2; exit 2; }
# Give a moment for server to start; check if alive
sleep 0.5
if ! ps -p "$pid" >/dev/null 2>&1; then
  echo "Preview server failed to start, last log lines:" >&2
  tail -n 200 "$LOG_FILE" >&2 || true
  rm -f "$PID_FILE" || true
  exit 6
fi
echo "$pid"
BASH
  chmod +x "$WS/preview.sh"
fi

echo "scaffold complete"
